### ISSUE TITLE
Issues when indexing WinForms

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/source-indexer#35]
https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/WindowsFormsSynchronizationContext.cs,17

the link to SynchronizationContext is still not working.

**Comment by stephentoub** [comment]
Or seemingly anything else in corefx/coreclr.

**Comment by KirillOsenkov** [comment]
This comment in particular I think summarizes the issues we're seeing:
https://github.com/aspnet/AspNetCore/issues/7281#issuecomment-461242879

**Comment by kirsan31** [comment]
Got here after I could not find `System.Windows.Forms` on source.dot.net.
Another one of many obstacles to the migration from .net to core :(

**Comment by KirillOsenkov** [comment]
@alexperovich indeed it looks like System.Windows.Forms.dll is missing from the index. Are there any errors in the log from SourceBrowser?

**Comment by alexperovich** [comment]
Yea, from the errors (https://source.dot.net/Errors.txt) it looks like winforms is hitting this issue https://github.com/dotnet/roslyn/issues/41763.

**Comment by KirillOsenkov** [comment]
It's weird though, there's a try/catch here that should prevent this bug from failing the entire project, it should just fail the current file:

https://github.com/dotnet/SourceBrowser/blob/6c21c6c1d7dae56a20dbf0f72d2e0cfa3f35caa6/src/HtmlGenerator/Pass1-Generation/Classifier.cs#L23-L27

https://github.com/dotnet/SourceBrowser/blob/6c21c6c1d7dae56a20dbf0f72d2e0cfa3f35caa6/src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs#L374

I'm thinking the NullRef in Roslyn is not the root cause, I see the following in the logs:
```
3/12/2020 2:04:49 PM: First chance exception while processing assembly: System.Windows.Forms
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.SourceBrowser.HtmlGenerator.DocumentGenerator.<GenerateHtml>d__18.MoveNext() in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\DocumentGenerator.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.SourceBrowser.HtmlGenerator.DocumentGenerator.<Generate>d__15.MoveNext() in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\DocumentGenerator.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.<>c__DisplayClass58_0.<<Generate>b__2>d.MoveNext() in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\ProjectGenerator.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by KirillOsenkov** [comment]
OK I see the problem, this line here doesn't handle null:
https://github.com/dotnet/SourceBrowser/blob/6c21c6c1d7dae56a20dbf0f72d2e0cfa3f35caa6/src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs#L154

I'll send a PR

**Comment by KirillOsenkov** [comment]
@alexperovich https://github.com/dotnet/SourceBrowser/pull/15 please ;)

**Comment by alexperovich** [comment]
I merged this change into source-indexer and triggered a build. It should be working in a few hours.

**Comment by KirillOsenkov** [comment]
Yay, it's fixed now! https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Form.cs,71d66965280a3f7b

Thanks all!
