### ISSUE TITLE
Some arities of ValueTuple<> aren't showing up in search

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#55]
https://source.dot.net/#q=valueTuple%3C
![image](https://user-images.githubusercontent.com/2642209/83656439-8ba46500-a58d-11ea-9eab-8c32a7bbcc4f.png)
Note that `ValueTuple<T1, T2>`, `ValueTuple<T1, T2, T3>`, etc. aren't showing up.

If, however, you navigate to one and click on it, references to it do show up, e.g.
https://source.dot.net/#System.Private.CoreLib/ValueTuple.cs,a4ad7dc5629aa617,references
![image](https://user-images.githubusercontent.com/2642209/83656471-96f79080-a58d-11ea-94ae-126bbcdbb8e8.png)

**Comment by alexperovich** [comment]
Thats really strange. I don't know much about how the search works though. @KirillOsenkov do you have any ideas?

**Comment by KirillOsenkov** [comment]
In my simple testing this should all work fine:

![image](https://user-images.githubusercontent.com/679326/83693819-a84f9580-a5ab-11ea-887e-e99721dbff7f.png)

I am noticing an OutOfMemory in https://source.dot.net/errors.txt:

```
Exception during Project file generation: F:\workspace\_work\1\s\bin\repo\winforms\src\System.Windows.Forms.Design\src\System.Windows.Forms.Design.csproj
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.InternalSubString(Int32 startIndex, Int32 length)
   at Microsoft.SourceBrowser.HtmlGenerator.XmlSupport.<>c__DisplayClass9_0.<Generate>b__1(Int32 start, Int32 length, SyntaxNode node, XmlClassificationTypes classification) in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\XmlSupport.cs:line 66
   at Microsoft.Language.Xml.ClassifierVisitor.Visit(SyntaxNode node, Int32 windowStart, Int32 windowLength, Action`4 resultCollector)
   at Microsoft.SourceBrowser.HtmlGenerator.XmlSupport.Generate(String sourceXmlFilePath, String destinationHtmlFilePath, String displayName) in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\XmlSupport.cs:line 59
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.GenerateXmlFile(String filePath) in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\ProjectGenerator.ProjectFile.cs:line 120
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.GenerateXmlFilesOfProjectItemType(Project msbuildProject, String itemType) in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\ProjectGenerator.ProjectFile.cs:line 100
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.GenerateResxFiles(Project msbuildProject) in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\ProjectGenerator.ProjectFile.cs:line 91
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.GenerateProjectFile() in F:\workspace\_work\1\s\src\SourceBrowser\src\HtmlGenerator\Pass1-Generation\ProjectGenerator.ProjectFile.cs:line 50
```

It might be a red herring or it might be related (??) This is also surprising since HtmlGenerator.exe is supposed to run as 64-bit (AnyCPU).

**Comment by KirillOsenkov** [comment]
All the searchable symbols are stored in https://source.dot.net/DeclaredSymbols.txt in a custom binary format. From a quick glance into the format all ValueTuples are there:

![image](https://user-images.githubusercontent.com/679326/83694169-59563000-a5ac-11ea-8b74-e968505f3f8f.png)

**Comment by KirillOsenkov** [comment]
OK I was able to reproduce in unit-tests:
![image](https://user-images.githubusercontent.com/679326/83695827-bc959180-a5af-11ea-9cc2-8b616920540c.png)

I'll investigate further.

**Comment by KirillOsenkov** [comment]
Ah, lol, here they are:
https://source.dot.net/#q=%28T1

**Comment by KirillOsenkov** [comment]
I'm leaning to won't fix, these are the names Roslyn returns and it'd be weird to put in a special case workaround just to fix this. The index is all intact and correct, it's just it happens to pick these names somewhere deep in the bowels of Roslyn.

**Comment by alexperovich** [comment]
That's really strange that roslyn is picking a different name for these types, but if that is what roslyn is returning then there isn't much we can do.

**Comment by stephentoub** [comment]
Ok. Thanks for investigating.

Just FYI @jaredpar in case this isn't by design.

**Comment by alexperovich** [comment]
I bet its intentional because the type is `ValueTuple<...>` the "friendly" name of concrete value tuples is `(T1, T2, T3)`. Its not happening for `ValueTuple<T1>` and `ValueTuple<T1, ... ,TRest>` because those aren't representable in `(...)` syntax.
